module.exports = {
  REQUESTED: 'REQUESTED',
  HIDE_MODAL: 'HIDE_MODAL',
  CLEAR_DETAILS: 'CLEAR_DETAILS',
  GET_GRID_LIST: 'GET_GRID_LIST',
  NETWORK_ERROR: 'NETWORK_ERROR',
  GET_ITEM_DETAILS: 'GET_ITEM_DETAILS'
}